# Generated by Django 3.0.7 on 2020-06-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=27)),
                ('attending', models.CharField(max_length=19)),
                ('not_attending', models.CharField(default='N/A', max_length=100)),
                ('favourite_song', models.CharField(max_length=100)),
                ('favourite_drink', models.CharField(default='', max_length=100)),
                ('dietary_requirements', models.CharField(default='N/A', max_length=100)),
                ('additional_info', models.TextField(default='N/A', max_length=2000)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
            },
        ),
    ]
