# Generated by Django 3.0.7 on 2020-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_homecarousel_villacarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'verbose_name': 'Home Carousel Image', 'verbose_name_plural': 'Home Carousel Images'},
        ),
        migrations.AlterModelOptions(
            name='villacarousel',
            options={'verbose_name': 'Villa Carousel Image', 'verbose_name_plural': 'Villa Carousel Images'},
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='additional_info',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='favourite_drink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='favourite_song',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='not_attending',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
