# Generated by Django 3.0.7 on 2020-07-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_auto_20200705_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='additional_info',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attending',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='favourite_drink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='favourite_song',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest_name',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='not_attending',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
